import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/navigation/navigation";
import Providers from './providers';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "FSTCK UI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Providers>
        <div className="relative">
          <header className="w-full">
            <Navigation/>
          </header>
          <main className="max-w-screen-xl m-auto mt-6 p-4">
            {children}
          </main>
        </div>
      </Providers>
      </body>
    </html>
  );
}
